name: Laravel Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupère le code source du package
    - uses: actions/checkout@v4

    # 2️⃣ Installe PHP 8.3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, bcmath

    # 3️⃣ Met en cache les dépendances Composer
    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-

    # 4️⃣ Installe les dépendances du package
    - name: Install Package Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    # 5️⃣ Crée un projet Laravel 12 pour tester le package
    - name: Create Temporary Laravel 12 Project
      run: composer create-project laravel/laravel temp-laravel "^12.0" --quiet

    # 6️⃣ Configure le package local comme dépôt de type path et l'installe
    - name: Configure Package in Temporary Project
      run: |
        cd temp-laravel
        composer config repositories.laravel-mapbox path ../
        composer require thomsult/laravel-mapbox:dev-main --prefer-source --no-interaction

    # 7️⃣ Copie le fichier .env et génère la clé d’application Laravel
    - name: Setup Environment
      run: |
        cd temp-laravel
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate

    # 8️⃣ Installe Pest si nécessaire et exécute les tests
    - name: Run Pest Tests
      run: |
        cd temp-laravel
        vendor/bin/pest ./vendor/thomsult/laravel-mapbox/tests --debug
