name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupère le code source
    - uses: actions/checkout@v4

    # 2️⃣ Installe PHP 8.3 et les extensions nécessaires
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, bcmath
        coverage: none

    # 3️⃣ Copie le fichier .env si absent
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # 4️⃣ Met en cache les dépendances Composer pour accélérer les builds
    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-

    # 5️⃣ Installe les dépendances PHP
    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    # 6️⃣ Génère la clé d’application Laravel
    - name: Generate Application Key
      run: php artisan key:generate

    # 7️⃣ Exécute les tests (avec Pest ou PHPUnit)
    - name: Run Tests
      run: composer test
