name: Laravel Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, bcmath

    # Installe Composer pour ton package
    - name: Install Package Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    # Crée un projet Laravel temporaire
    - name: Create Temporary Laravel Project
      run: composer create-project laravel/laravel temp-laravel "^10.0" --quiet

    # Installe ton package dans le projet temporaire
    - name: Install Package in Temporary Project
      run: |
        cd temp-laravel
        composer require ../

    # Génère la clé d'application dans le projet temporaire
    - name: Generate Application Key
      run: |
        cd temp-laravel
        php artisan key:generate

    # Exécute les tests du package
    - name: Run Tests
      run: |
        cd temp-laravel/vendor/thomsult/laravel-mapbox
        composer test
